services:
  - type: web
    name: typeo
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: free
    healthCheckPath: /